[env:esp32-s3-devkitm-1]
platform = espressif32 @ 6.6.0  ; or latest
board = esp32-s3-devkitm-1
framework = arduino
monitor_speed = 115200
board_build.f_cpu = 240000000L
lib_ldf_mode = deep
lib_deps =
    https://github.com/me-no-dev/ESPAsyncWebServer.git
    https://github.com/me-no-dev/AsyncTCP.git
    https://github.com/sparkfun/SparkFun_Qwiic_OTOS_Arduino_Library.git
    https://github.com/arduino-libraries/Servo.git
    https://github.com/PowerBroker2/ArduPID.git
build_unflags =
    -std=gnu++11
build_flags =
    -std=gnu++14
    -D ARDUINO_USB_CDC_ON_BOOT=1
    -D ARDUINO_USB_MODE=1
    -D CONFIG_BT_ENABLED=0